apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rocketship.engine.fullname" . }}
  labels:
    {{- include "rocketship.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.engine.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rocketship.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: engine
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rocketship.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: engine
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: engine
          image: "{{ .Values.engine.image.repository }}:{{ .Values.engine.image.tag }}"
          imagePullPolicy: {{ .Values.engine.image.pullPolicy }}
          env:
            - name: TEMPORAL_HOST
              value: {{ .Values.temporal.host | quote }}
            - name: TEMPORAL_NAMESPACE
              value: {{ .Values.temporal.namespace | quote }}
            {{- $engineDBSecret := .Values.engine.database.secretName }}
            {{- if and .Values.postgres.enabled (eq $engineDBSecret "") }}
            {{- $engineDBSecret = include "rocketship.authbroker.databaseSecretName" . -}}
            {{- end }}
            {{- $engineDBKey := default "DATABASE_URL" .Values.engine.database.secretKey -}}
            {{- if ne $engineDBSecret "" }}
            - name: ROCKETSHIP_ENGINE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ $engineDBSecret }}
                  key: {{ $engineDBKey }}
            {{- else if .Values.engine.database.url }}
            - name: ROCKETSHIP_ENGINE_DATABASE_URL
              value: {{ .Values.engine.database.url | quote }}
            {{- end }}
            {{- range .Values.engine.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- $oidcMode := .Values.auth.oidc.mode | default .Values.auth.mode }}
            {{- $modeLower := lower $oidcMode }}
            {{- $oidcEnabled := or .Values.auth.oidc.enabled (or (eq $modeLower "github") (eq $modeLower "oidc")) }}
            {{- if $oidcEnabled }}
            - name: ROCKETSHIP_AUTH_MODE
              value: "oidc"
            {{- $issuer := coalesce .Values.auth.oidc.issuer .Values.auth.broker.issuer }}
            {{- if $issuer }}
            - name: ROCKETSHIP_OIDC_ISSUER
              value: {{ $issuer | quote }}
            {{- end }}
            {{- $clientID := coalesce .Values.auth.oidc.clientID .Values.auth.broker.clientID }}
            {{- if $clientID }}
            - name: ROCKETSHIP_OIDC_CLIENT_ID
              value: {{ $clientID | quote }}
            {{- end }}
            {{- $audience := coalesce .Values.auth.oidc.audience .Values.auth.broker.audience }}
            {{- if $audience }}
            - name: ROCKETSHIP_OIDC_AUDIENCE
              value: {{ $audience | quote }}
            {{- end }}
            {{- $brokerHost := printf "http://%s:%v" (include "rocketship.authbroker.fullname" .) .Values.auth.broker.service.port }}
            {{- $deviceEndpoint := coalesce .Values.auth.oidc.deviceEndpoint (ternary (printf "%s/device/code" $brokerHost) "" (eq $modeLower "github")) }}
            {{- if $deviceEndpoint }}
            - name: ROCKETSHIP_OIDC_DEVICE_ENDPOINT
              value: {{ $deviceEndpoint | quote }}
            {{- end }}
            {{- $tokenEndpoint := coalesce .Values.auth.oidc.tokenEndpoint (ternary (printf "%s/token" $brokerHost) "" (eq $modeLower "github")) }}
            {{- if $tokenEndpoint }}
            - name: ROCKETSHIP_OIDC_TOKEN_ENDPOINT
              value: {{ $tokenEndpoint | quote }}
            {{- end }}
            {{- $jwksEndpoint := coalesce .Values.auth.oidc.jwksURL (ternary (printf "%s/.well-known/jwks.json" $brokerHost) "" (eq $modeLower "github")) }}
            {{- if $jwksEndpoint }}
            - name: ROCKETSHIP_OIDC_JWKS_URL
              value: {{ $jwksEndpoint | quote }}
            {{- end }}
            {{- if .Values.auth.oidc.scopes }}
            - name: ROCKETSHIP_OIDC_SCOPES
              value: {{ join " " .Values.auth.oidc.scopes | quote }}
            {{- else if .Values.auth.broker.scopes }}
            - name: ROCKETSHIP_OIDC_SCOPES
              value: {{ join " " .Values.auth.broker.scopes | quote }}
            {{- end }}
            {{- if .Values.auth.oidc.allowedAlgorithms }}
            - name: ROCKETSHIP_OIDC_ALLOWED_ALGS
              value: {{ join "," .Values.auth.oidc.allowedAlgorithms | quote }}
            {{- end }}
            {{- end }}
          ports:
            - name: grpc
              containerPort: {{ .Values.engine.service.grpcPort }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.engine.service.httpPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          {{- with .Values.engine.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.engine.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.engine.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.engine.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
